version: '3.7'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
            container_name: GraphCms
            ports:
                - '3000:3000'
            volumes:
                - .:/app
                - /app/node_modules
