version: '3.7'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                DEVELOPMENT_MODE: ${DEVELOPMENT_MODE}
        container_name: GraphCms
        ports:
            - '3000:3000'
        volumes:
            - .:/app
            - /app/node_modules
            - /app/.next
        environment:
            - DEVELOPMENT_MODE=${DEVELOPMENT_MODE}

    nginx:
        image: nginx:latest
        ports:
            - '80:80'
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
