version: '3.7'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                DEVELOPMENT_MODE: ${DEVELOPMENT_MODE}
        container_name: GraphCms
        ports:
            - '80:3000'
        volumes:
            - .:/app
            - /app/node_modules
            - /app/.next
        environment:
            - DEVELOPMENT_MODE=${DEVELOPMENT_MODE}
